neovim_lua_module(
    name = "lua",
    srcs = ["please.lua"],
    deps = [
        "//lua/please:cursor",
        "//lua/please:debug",
        "//lua/please:logging",
        "//lua/please:parsing",
        "//lua/please:parsingv2",
        "//lua/please:query",
        "//lua/please/runners",
        "//third_party/neovim:plenary",
    ],
)
