neovim_lua_module(
    name = "lua",
    srcs = ["please.lua"],
    deps = [
        "//lua/please:debug",
        "//lua/please:logging",
        "//lua/please:parsing",
        "//lua/please:plz",
        "//lua/please:query",
        "//lua/please:runner",
    ],
)
