plugin_repo(
    name = "cc",
    owner="marcuscaisey",
    plugin = "cc-rules",
    revision = "noall_load-fix",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    revision = "v1.5.0",
)

plugin_repo(
    name = "go",
    plugin = "go-rules",
    revision = "v1.11.4",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.2.0",
)
