neovim_test(
    name = "parsing_spec",
    test_file = "parsing_spec.lua",
    deps = [
        "//lua/please:cursor",
        "//lua/please:parsing",
        "//tests/utils:temptree",
    ],
)

neovim_test(
    name = "query_spec",
    test_file = "query_spec.lua",
    deps = [
        "//lua/please:query",
        "//tests/utils:temptree",
    ],
)

