export_file(
    name = "neovim",
    src = "neovim.build_defs",
    visibility = ["PUBLIC"],
)

export_file(
    name = "neovim_test_runner",
    src = "neovim_test_runner.lua",
    visibility = ["PUBLIC"],
)

export_file(
    name = "neovim_test_init",
    src = "neovim_test_init.lua",
    visibility = ["PUBLIC"],
)
