filegroup(
    name = "file1",
    srcs = ["file1.txt"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "file2",
    srcs = ["file2.txt"],
    visibility = ["PUBLIC"],
)

if True:
    filegroup(
        name = "all_files",
        srcs = ["file1.txt", "file2.txt"],
        visibility = ["PUBLIC"],
    )
