name: Check Neovim Toolchain Versions
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_call:
  workflow_dispatch:

jobs:
  check-neovim-toolchain-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        uses: ./.github/actions/apply-apparmor-profile
      - name: Run toolchain version check
        run: ./pleasew run //scripts:check_neovim_toolchain_version
