name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-typecheck-lua:
    name: Test and Typecheck Lua
    uses: ./.github/workflows/test-typecheck-lua.yaml

  check-neovim-toolchain-versions:
    name: Check Neovim Toolchain Versions
    uses: ./.github/workflows/check-neovim-toolchains-versions.yaml

  lint-lua:
    name: Lint Lua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Lint with Stylua
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check --color always .

  lint-build:
    name: Lint BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Lint with plz format
        run: |
          ./pleasew format --write
          if ! git diff --quiet; then
              echo 'The following files need to be formatted with "plz format --write"':
              git --no-pager diff --name-only
              exit 1
          fi
