name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@main
      - name: Install Please
        run: curl https://get.please.build | bash && echo ~/.please >> $GITHUB_PATH
      - name: Apply AppArmor profile
        run: |
          ls -al ~/.please
          sudo cp .github/workflows/apparmor_profile /etc/apparmor.d/build.please
          sudo systemctl reload apparmor
          sudo aa-complain plz
      - name: Run tests
        run: |
          plz test || echo failed
          cat /var/log/syslog
  lint-lua:
    name: Lint Lua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@main
      - name: Lint with Stylua
        uses: JohnnyMorganz/stylua-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check --color always .
  lint-build:
    name: Lint BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@main
      - name: Install Please
        run: curl https://get.please.build | bash && echo ~/.please >> $GITHUB_PATH
      - name: Lint with plz format
        run: |
          plz format --write
          if ! git diff --quiet; then
              echo 'The following files need to be formatted with "plz format --write"':
              git --no-pager diff --name-only
              exit 1
          fi
