name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  list-neovim-toolchains:
    name: List Neovim Toolchains
    runs-on: ubuntu-latest
    outputs:
      toolchains: ${{ steps.generate-toolchain-list.outputs.toolchains }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        uses: ./.github/actions/apply-apparmor-profile
      - name: Generate toolchain list
        id: generate-toolchain-list
        run: echo toolchains=$(./pleasew run //tools:neovim_toolchains) >> "$GITHUB_OUTPUT"

  test-plugin:
    name: Test Plugin (Neovim ${{ matrix.toolchain.version }})
    needs: list-neovim-toolchains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        uses: ./.github/actions/apply-apparmor-profile
      - name: Run tests
        run: ./pleasew --override buildconfig.nvim-tool:'${{ matrix.toolchain.nvim }}' --include neovim_test test
    strategy:
      matrix:
        toolchain: ${{ fromJSON(needs.list-neovim-toolchains.outputs.toolchains) }}
      fail-fast: false

  test-other:
    name: Test Other
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        uses: ./.github/actions/apply-apparmor-profile
      - name: Run tests
        run: ./pleasew --exclude neovim_test test

  typecheck-lua-code:
    name: Typecheck Lua Code (Neovim ${{ matrix.toolchain.version }})
    needs: list-neovim-toolchains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        uses: ./.github/actions/apply-apparmor-profile
      - name: Install dependencies
        run: ./pleasew build ${{ matrix.toolchain.target }} //third_party/neovim:plugins
      - name: Run Lua typecheck
        uses: mrcjkb/lua-typecheck-action@main
        env:
          TOOLCHAIN_TARGET_NAME: ${{ matrix.toolchain.target_name }}
    strategy:
      matrix:
        toolchain: ${{ fromJSON(needs.list-neovim-toolchains.outputs.toolchains) }}
      fail-fast: false

  lint-lua-code:
    name: Lint Lua Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check --color always .

  lint-build-files:
    name: Lint BUILD Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        uses: ./.github/actions/apply-apparmor-profile
      - name: Run BUILD file linter
        run: ./pleasew run //tools:lint_build_files

  check-neovim-toolchain-versions:
    name: Check Neovim Toolchain Versions
    uses: ./.github/workflows/check-neovim-toolchain-versions.yaml
