name: CI
on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Install Please
        run: curl https://get.please.build | bash && echo ~/.please >> $GITHUB_PATH
      - name: Apply AppArmor profile
        run: |
          sudo cp .github/workflows/please.please_sandbox /etc/apparmor.d
          sudo systemctl reload apparmor.service
      - name: Run tests
        run: plz test
  lint-lua:
    name: Lint Lua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Lint with Stylua
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check --color always .
  typecheck-lua:
    name: Typecheck Lua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        run: |
          sudo cp .github/workflows/please.please_sandbox /etc/apparmor.d
          sudo systemctl reload apparmor.service
      - name: Install dependencies
        run: ./pleasew build //third_party/neovim:toolchain_0_12_0 //third_party/neovim:nvim_dap
      - name: Typecheck with lua-language-server
        uses: mrcjkb/lua-typecheck-action@main
        with:
          directories: .
          configpath: .luarc.json
  lint-build:
    name: Lint BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Install Please
        run: curl https://get.please.build | bash && echo ~/.please >> $GITHUB_PATH
      - name: Lint with plz format
        run: |
          plz format --write
          if ! git diff --quiet; then
              echo 'The following files need to be formatted with "plz format --write"':
              git --no-pager diff --name-only
              exit 1
          fi
