name: Test and Typecheck Lua Code
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_call:
  workflow_dispatch:

jobs:
  list-neovim-toolchains:
    name: List Neovim Toolchains
    runs-on: ubuntu-latest
    outputs:
      toolchains: ${{ steps.generate-toolchain-list.outputs.toolchains }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        run: |
          sudo cp .github/workflows/please.please_sandbox /etc/apparmor.d
          sudo systemctl reload apparmor.service
      - name: Generate toolchain list
        id: generate-toolchain-list
        run: echo toolchains=$(python3 scripts/neovim_toolchains.py) >> "$GITHUB_OUTPUT"

  test:
    name: Test (Neovim ${{ matrix.toolchain.version }})
    needs: list-neovim-toolchains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        run: |
          sudo cp .github/workflows/please.please_sandbox /etc/apparmor.d
          sudo systemctl reload apparmor.service
      - name: Run tests
        run: ./pleasew --override buildconfig.nvim-tool:'${{ matrix.toolchain.nvim }}' test
    strategy:
      matrix:
        toolchain: ${{ fromJSON(needs.list-neovim-toolchains.outputs.toolchains) }}
      fail-fast: false

  typecheck-lua-code:
    name: Typecheck Lua Code (Neovim ${{ matrix.toolchain.version }})
    needs: list-neovim-toolchains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v6
      - name: Apply AppArmor profile
        run: |
          sudo cp .github/workflows/please.please_sandbox /etc/apparmor.d
          sudo systemctl reload apparmor.service
      - name: Install dependencies
        run: ./pleasew build ${{ matrix.toolchain.target }} //third_party/neovim:plugins
      - name: Run Lua typecheck
        uses: mrcjkb/lua-typecheck-action@main
        env:
          TOOLCHAIN_TARGET_NAME: ${{ matrix.toolchain.target_name }}
    strategy:
      matrix:
        toolchain: ${{ fromJSON(needs.list-neovim-toolchains.outputs.toolchains) }}
      fail-fast: false
