neovim_lua_module(
    name = "mock",
    srcs = ["mock.lua"],
    deps = [
        "//lua/please/runners",
        "//lua/please:plz",
        "//third_party/neovim:plenary",
    ],
)

neovim_lua_module(
    name = "temptree",
    srcs = ["temptree.lua"],
    deps = [
        "//third_party/neovim:plenary",
    ],
)
